// <auto-generated />
using System;
using Karya.Test.Web.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Karya.Test.Web.Api.Migrations
{
    [DbContext(typeof(DevContext))]
    [Migration("20260623115034_inventory-detail")]
    partial class inventorydetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Karya.Test.Web.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.Inventory", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MainCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "MainCategoryId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.InventoryCategory", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("MainCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "MainCategoryId");

                    b.ToTable("InventoryCategories");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.InventoryDetail", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InventoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InventoryTenantId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MainCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("InventoryTenantId", "InventoryId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "InventoryId");

                    b.HasIndex("TenantId", "MainCategoryId");

                    b.ToTable("InventoryDetail");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.InventoryMainCategory", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "Id");

                    b.ToTable("InventoryMainCategory");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.Inventory", b =>
                {
                    b.HasOne("Karya.TestApi.Entities.InventoryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Karya.TestApi.Entities.InventoryMainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("TenantId", "MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.InventoryCategory", b =>
                {
                    b.HasOne("Karya.TestApi.Entities.InventoryMainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("TenantId", "MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.InventoryDetail", b =>
                {
                    b.HasOne("Karya.TestApi.Entities.Inventory", null)
                        .WithMany("InventoryDetails")
                        .HasForeignKey("InventoryTenantId", "InventoryId");

                    b.HasOne("Karya.TestApi.Entities.InventoryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Karya.TestApi.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("TenantId", "InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Karya.TestApi.Entities.InventoryMainCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("TenantId", "MainCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Inventory");

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Karya.TestApi.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
