<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>Karya.Core</PackageId>
	<Version>1.0.1</Version>
	<Authors>Ramazan Karagoz</Authors>
	<Company>Karagoz</Company>
	<Description>Karya Core Library - .NET 10 with all dependencies</Description>
	<PackageTags>karya;core;entityframework;mapster</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageProjectUrl>https://github.com/karagozr/KaryaCore</PackageProjectUrl>
	<RepositoryUrl>https://github.com/karagozr/KaryaCore</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExtreme.AspNet.Data" Version="5.1.0" />
    <PackageReference Include="Mapster" Version="10.0.7" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <!--<PackageReference Include="System.Formats.Asn1" Version="10.0.1" />-->
  </ItemGroup>

</Project>
